In [1]:
import numpy as np

Following this exposition:

http://fourier.eng.hmc.edu/e161/lectures/algebra/node7.html

In [2]:
A = np.array(
    [[ 26167692.,  -8722564.,         0., -17445128.,         0.],
    [ -8722564.,  43612820.,         0., -17445128.,         0.],
    [        0.,         0.,         0.,         0.,         0.],
    [-17445128., -17445128.,         0.,  43612820.,         0.],
    [        0.,         0.,         0.,         0.,         0.]])

In [3]:
B = np.array(
    [[342.360637  , 114.12021233,   0.        ,  57.06010617, 0.        ],
    [114.12021233, 456.48084933,   0.        ,  57.06010617, 0.        ],
    [  0.        ,   0.        , 456.48084933,   0.        , 57.06010617],
    [ 57.06010617,  57.06010617,   0.        , 456.48084933,  0.        ],
    [  0.        ,   0.        ,  57.06010617,   0.        ,456.48084933]])

Solve the Eigenvalue problem for B.

In [4]:
B_evalues, B_evectors = np.linalg.eig(B)

Check.

In [5]:
B_evectors.T @ B_evectors

array([[  1.00000000e+00,   3.21151247e-17,   1.22671915e-16,
         -8.91864294e-17,  -2.95770560e-16],
       [  3.21151247e-17,   1.00000000e+00,  -2.07372726e-17,
          6.33719977e-17,   4.24692842e-17],
       [  1.22671915e-16,  -2.07372726e-17,   1.00000000e+00,
          9.55400436e-15,  -8.86498157e-16],
       [ -8.91864294e-17,   6.33719977e-17,   9.55400436e-15,
          1.00000000e+00,  -1.79380389e-16],
       [ -2.95770560e-16,   4.24692842e-17,  -8.86498157e-16,
         -1.79380389e-16,   1.00000000e+00]])

Define $\Phi^{'}_B$

In [6]:
phi_B_prime = B_evectors @ np.diag(1 / np.sqrt(B_evalues))

Check.

In [7]:
phi_B_prime.T @ B @ phi_B_prime

array([[  1.00000000e+00,  -4.24867176e-16,   8.43560572e-17,
         -1.07302789e-16,  -3.13830351e-16],
       [ -3.69453508e-16,   1.00000000e+00,  -1.19209756e-16,
          5.20760256e-17,   3.07781945e-17],
       [ -3.09899213e-17,  -1.00979270e-16,   1.00000000e+00,
          9.64936560e-15,  -7.89621434e-16],
       [ -1.07302789e-16,   5.20760256e-17,   9.64936560e-15,
          1.00000000e+00,  -5.89374392e-17],
       [ -3.13830351e-16,   3.07781945e-17,  -7.89621434e-16,
          4.58211201e-17,   1.00000000e+00]])

Apply the same transformation to $A$.

In [8]:
A_prime = phi_B_prime.T @ A @ phi_B_prime

Diagonalize $A'$.

In [9]:
A_prime_evalues, A_prime_evectors = np.linalg.eig(A_prime)

Define $\Phi$.

In [10]:
phi = B_evectors @ np.diag(1 / np.sqrt(B_evalues)) @ A_prime_evectors

$\Phi$ also diagonalizes B?

In [11]:
phi.T @ B @ phi

array([[  1.00000000e+00,  -3.26177827e-16,   5.35777506e-19,
         -7.23930150e-16,  -5.37335533e-16],
       [ -2.57280002e-16,   1.00000000e+00,   2.55803612e-06,
         -1.42947879e-15,  -9.47972793e-16],
       [ -4.55477178e-17,   2.55803612e-06,   1.00000000e+00,
          9.06569060e-15,   7.32890428e-15],
       [ -7.23930150e-16,  -1.42947879e-15,   9.06569060e-15,
          1.00000000e+00,   5.34987404e-01],
       [ -5.37335533e-16,  -9.47972793e-16,   7.32890428e-15,
          5.34987404e-01,   1.00000000e+00]])

$\Phi$ is the solution.

In [12]:
A @ phi

array([[  1.83683188e+05,   1.60395552e+06,   1.02120583e+06,
          8.74314534e-16,  -3.02464843e-15],
       [  1.83683188e+05,  -2.01778267e+06,   1.48688775e+06,
          9.00820213e-16,  -4.52455787e-15],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  1.83683188e+05,  -3.19653445e+05,  -2.48598535e+06,
         -1.82845168e-15,   7.53960073e-15],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00]])

In [13]:
B @ phi @ np.diag(A_prime_evalues)

array([[  1.83683188e+05,   1.60395552e+06,   1.02120583e+06,
         -1.61926793e-41,  -1.25012514e-39],
       [  1.83683188e+05,  -2.01778267e+06,   1.48688775e+06,
         -1.66964349e-41,  -1.92893641e-39],
       [ -1.14378467e-10,  -2.16050457e-09,   1.85267732e-08,
         -1.97997899e-20,   1.43579923e-18],
       [  1.83683188e+05,  -3.19653445e+05,  -2.48598535e+06,
          3.51749354e-41,   3.53091773e-39],
       [  1.64627557e-10,   3.89594604e-09,  -2.24936646e-08,
          5.58942435e-20,  -1.68899184e-19]])